### ISSUE TITLE
Implement BackgroundService

### ISSUE THREAD

**Issue by rianjs** [rianjs/RepoInspector#7]
The collection of things that do work are tee'd up. Just needs to be tucked into a background service thing.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.backgroundservice?view=dotnet-plat-ext-5.0

**Comment by bojanrajkovic** [comment]
Why `BackgroundService`, and not just a daemon that wires up the DI/etc. machinery? AFAICT, `BackgroundService` is intended for background services inside web apps, not standalone daemons.

**Comment by rianjs** [comment]
Per our conversation elsewhere: screw it.
