### ISSUE TITLE
WordCount is a proxy for something else

### ISSUE THREAD

**Issue by rianjs** [rianjs/RepoInspector#9]
There's a type called `WordCounter` that implements `IWordCounter` which is really just a wrapper for a regex. `IWordCounter` is the wrong thing, though. (The interface is really just for mockability.)

The original idea was that counting words in comments was a proxy for a healthy dialog, and I think that remains true to a very great extent. _But there other things that could be useful to take note of that speak to the robustness of the community surrounding a repository._

* Number of code blocks (`tripleTick.Count / 2` in a comment)
* Number of code fragments with single ticks ( `(tick.Count - (tripleTick.Count * 3)) / 2` I think)
* References to other issues, pull requests, etc. (In GitHub, a PR is just an issue with code attached.)

So while I think word count is a good thing to continue, the idea it's speaking to is something else. "Expressiveness", "semantic density", "semantic richness" -- none of these are perfect articulations, but they're closer. I don't have a good name right now.

Or maybe that's too vague, and we should just go with scores? Something like...

* 0.1 points per word
* 10 points for a code block
* 2 points for a code fragment
* 2 points for a URL
* 5 points for a link to an issue or PR
* Maybe something that accounts for time to closure. Maybe 5 points if closed in 24 hours, 4 if in 48, etc. down to 0 points.

And then sum it all up, and that's the _community health score_ associated with your PR. And we'd expect to see a great deal of variance in the scores: if there's always a ton of comments, there's probably a problem with your team, and someone is probably overworked keeping them in check. If there are no comments, then you have issues, too. So we'd expect to find a healthy spread of scores.

Again, we're not trying to measure code quality, we're trying to measure _community health_. So 100 comments on an intern's PR actually reflects well _on the context in which they exist_, which is what we're trying to quantify.

**Comment by rianjs** [comment]
The idea of scoring is really appealing to me, and I don't see the unbounded nature of a score as being problematic because we're going to apply statistical measures that will provide context. I think I'm going to play with this idea a little bit.

**Comment by bojanrajkovic** [comment]
I like the idea of scoring, and it's pretty trivial. Mean, median, stdev, and some % of PRs with scores within 1/2/3 sigmas seems like an interesting proxy.

Would be good to correlate it to PR size somehow, too, or at least normalize against the total diff stat (removed+added lines), maybe just as simple as `score / (removed+added)` -- naturally, you'd expect small PRs to have smaller absolute scores.
